version: '3'

services:
  node0:
    container_name: node0
    image: "cometbft/localnode"
    ports:
      - "26656-26657:26656-26657"
      - "26670:26660"
    environment:
      - ID=0
      - LOG=${LOG:-cometbft.log}
    volumes:
      - ./build:/cometbft:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  node1:
    container_name: node1
    image: "cometbft/localnode"
    ports:
      - "26659-26660:26656-26657"
      - "26671:26660"
    environment:
      - ID=1
      - LOG=${LOG:-cometbft.log}
    volumes:
      - ./build:/cometbft:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  node2:
    container_name: node2
    image: "cometbft/localnode"
    environment:
      - ID=2
      - LOG=${LOG:-cometbft.log}
    ports:
      - "26661-26662:26656-26657"
      - "26672:26660"
    volumes:
      - ./build:/cometbft:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  node3:
    container_name: node3
    image: "cometbft/localnode_stuff"
    environment:
      - ID=3
      - LOG=${LOG:-cometbft.log}
    ports:
      - "26663-26664:26656-26657"
      - "26673:26660"
    volumes:
      - ./build:/cometbft:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.5

  node4:
    container_name: node4
    image: "cometbft/localnode"
    environment:
      - ID=4
      - LOG=${LOG:-cometbft.log}
    ports:
      - "26665-26666:26658-26659"
      - "26674:26660"
    volumes:
      - ./build:/cometbft:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  node5:
    container_name: node5
    image: "cometbft/localnode"
    environment:
      - ID=5
      - LOG=${LOG:-cometbft.log}
    ports:
      - "26667-26668:26660-26661"
      - "26675:26660"
    volumes:
      - ./build:/cometbft:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.7

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.0.0/16
